Post/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name = 'Post'

urlpatterns = [
		path('', views.home, name='home'),
		path('<int:post_id>/', views.post_view, name='post_view'),
		path('post-home', views.posthome, name='posthome'),
		path('admin_postlist', views.admin_postlist, name='admin_postlist'),
		path('delete/<int:id>/', views.post_delete, name='post_delete'),
		path('editpost', views.editpost, name='editpost'),
		path('update/<int:id>/', views.editpost, name='post_update'),
		path('imageList/<int:id>/', views.imageList, name='imageList'),
		path('image/update/<int:id>', views.image_update, name='image_update'),
		path('image/delete/<int:id>/', views.image_delete, name='image_delete'),

	]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PostApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Post.urls')),
    path('members/', include('django.contrib.auth.urls')),  
    path('members/', include('members.urls')),
    
   
	path("ckeditor5/", include('django_ckeditor_5.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'members'

urlpatterns = [
	path('login_user', views.login_user, name='login'),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Post/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.dispatch import receiver
from django.db.models.signals import post_save
from django_ckeditor_5.fields import CKEditor5Field
import datetime


# Create your models here.

from django.db import models

def get_upload_path(instance, filename):
    model = instance.album.model.__class__._meta
    name = model.verbose_name_plural.replace(' ', '_')
    album = instance.album.name
    return f'post/images/{name}/{album}/images/{filename}'

class Category(models.Model):
    name = models.CharField(max_length=255,blank=True, null=True)
    image = models.ImageField(null=True, blank=True,upload_to="post/images/category")
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=255,blank=True, null=True)
    def __str__(self):
        return self.name

class Album(models.Model):
    name = models.CharField(max_length=255,null=True,unique = True)

    def default(self):
        return self.images.filter(default=True).first()
    def thumbnails(self):
        return self.images.filter(width__lt=100, length_lt=100)
    def __str__(self):
        return self.name

   

@receiver(post_save,sender=Album)
def create_post(sender,instance,created,**kwargs):
    if created:
        post.objects.create(album=instance, title=instance.name, date_created=(datetime.datetime.now()), last_edit_date=(datetime.datetime.now()))
        

@receiver(post_save,sender=Album)
def update_post(sender,instance,created,**kwargs):
    if created == False:
        instance.post.save()
        


class Image(models.Model):
    order = models.FloatField(null=True,blank=True)
    description=models.CharField(max_length=200,null=True,blank=True)
    image = models.ImageField(upload_to=get_upload_path)
    default = models.BooleanField(default=False)
  
    album = models.ForeignKey(Album, related_name='images', on_delete=models.CASCADE)
    def __int__(self):
        return self.order

class Author(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="the_author",
        on_delete=models.CASCADE,)
    
    title=models.CharField(max_length=100,null=True,blank=True)
    image=models.ImageField(upload_to=f"post/images/authors")

    def __str__(self):
        return self.user.username


class post(models.Model):

    title= models.CharField(max_length=200,null=True,blank=True)
    date_created= models.DateField(null=True,blank=True)
    last_edit_date= models.DateField(null=True,blank=True)
    author = models.ForeignKey(Author, null=True,blank=True, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True,blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag)
    text= CKEditor5Field('Text', config_name='extends',null=True,blank=True) 
    HomePage=models.BooleanField(default=False)
    FeaturedPost=models.BooleanField(default=False)
    album = models.OneToOneField(Album, related_name='model', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

Post/forms.py
from django.forms.widgets import CheckboxSelectMultiple
from django import forms

from .models import *

from django.forms.models import ModelForm





class PostForm(forms.ModelForm):
    
	class Meta:
      
		model = post
		
       
		fields = ('title','author','category','tags','text','album','HomePage','FeaturedPost')				
		labels = {
			'title':'Title',
			'author':'Author',
			'category':'Category',
			'text':'Text',
			'tags': 'Tags',
			'date_created':'Date Created',
			'album':"Album",
            'HomePage':'Home Page',
			'FeaturedPost':'Featured Post',
		}
	
		
		
	def __init__(self, *args, **kwargs):
			
			super(PostForm, self).__init__(*args, **kwargs)
			
			self.fields["tags"].widget = CheckboxSelectMultiple()
			self.fields["tags"].queryset = Tag.objects.all()
		

class ImageForm(forms.ModelForm):
	class Meta:
		model = Image
		fields = ('order','description','image','default')
		labels = {
			'order':'Order',
			'description':'Description',
			'image':'Image',
			'default':'Default',
		}
		
	def __init__(self, *args, **kwargs):
			super().__init__(*args, **kwargs)
			self.fields['order'].widget.attrs.update({'placeholder': '1,2,3..'})
			self.fields['description'].widget.attrs.update({'placeholder': 'Brief Description'})
		
    		
      
class NewPostForm(forms.ModelForm):
	class Meta:
		model = Album
		fields = ('__all__')

class checkboxtags(forms.Form):
	
	tags = forms.ModelMultipleChoiceField(
		queryset=Tag.objects.all(),
		to_field_name='id',
		widget=forms.CheckboxSelectMultiple()
		)
		
	

Post/views/admin_imagelist.py
from django.contrib.auth.decorators import login_required
from Post.decorators import allowed_users
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from Post.forms import *
import os
from Post.models import post, Author,Album

@login_required
@allowed_users(allowed_roles=['Editor'])
def imageList(request, id):
    if request.method == "GET":        
        form = ImageForm
        images=Image.objects.filter(album=id).all()
        context = {'images':images,'form':form}
    
        return render(request, 'imageList.html',context)
    else:
        form = new_func(request)
        if form.is_valid():
            udate=form.save(commit=False)
            addalbum=Album.objects.get(id=id)
            udate.album = addalbum
            udate.save()           
            print("image saved")
        else:
            print("image not saved")
            print(form.errors)
        images=Image.objects.filter(album=id).all()
        form=ImageForm
        context = {'images':images,'form':form}
        return redirect(reverse_lazy('Post:imageList', kwargs={'id': id}),context)

@login_required
@allowed_users(allowed_roles=['Editor'])
def new_func(request):
    #need request.FILES for images
    form = ImageForm(request.POST,request.FILES)
    return form

@login_required
@allowed_users(allowed_roles=['Editor'])
def image_delete(request,id):
    selected_image = Image.objects.get(pk=id)
    curalbum = selected_image.album.id
    selected_image.delete()
    print(curalbum)
    return redirect(reverse_lazy('Post:imageList', kwargs={'id': curalbum}))

@login_required
@allowed_users(allowed_roles=['Editor'])    
def image_update(request, id=0):
    #if we are trying to view edit page. If new just show blank form, else show form with 
    # current data in it
    imageupdate= Image.objects.get(pk=id) 
    old_image_path = imageupdate.image.path
   

    if request.method == "GET":               
        curalbum = imageupdate.album.id  # used to get id for link to return to images in album        
        form = ImageForm(instance=imageupdate)
        context = {'curalbum':curalbum,'form':form}
        return render(request, 'edit_image.html', context)
    #from the form page we hit submit
    else:   
        # editing a existing image    
        
        curalbum = imageupdate.album.id
        form = ImageForm(request.POST,request.FILES, instance = imageupdate)
   
        if form.is_valid():         
             # deleting old uploaded image.
            image_path = imageupdate.image.path
            print(old_image_path)
            print(image_path)
            if os.path.exists(old_image_path):
                if old_image_path != image_path:
                    print("deleting old image")
                    os.remove(old_image_path)          
            update=form.save(commit=False)
            update.album = imageupdate.album            
            update.save()
            
            
        else:
           
            print(form.errors)
            return render(request, 'edit_image.html',{'form':form})
        
        return redirect(reverse_lazy('Post:imageList', kwargs={'id': curalbum}))

Post/views/admin_postlist.py
from django.contrib.auth.decorators import login_required
from Post.decorators import allowed_users
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from Post.forms import *
from django.contrib import messages
import datetime
from Post.filters import OrderFilter

from Post.models import post, Author,Album

@login_required
@allowed_users(allowed_roles=['Editor'])
def admin_postlist(request):
    
   
    if request.method == "GET":
        posts=post.objects.all().order_by('-date_created')
        form=NewPostForm
        return render(request, 'admin_postlist.html', {'posts':posts,'form':form})
    else:
        form = new_func(request)
        if form.is_valid():
            form.save()
            messages.success(request, 'Item Created')
            posts=post.objects.all().order_by('-date_created')
            form=NewPostForm
            return redirect(reverse_lazy('Post:admin_postlist'),{'posts':posts,'form':form})
            
        else:  
            print('did not save') 
            print(form.errors)  
            messages.error(request, 'Invalid form submission.')
            messages.error(request, form.errors)
            posts=post.objects.all().order_by('-date_created')
            form=NewPostForm
            return redirect(reverse_lazy('Post:admin_postlist'),{'posts':posts,'form':form })

@login_required
@allowed_users(allowed_roles=['Editor'])
def new_func(request):
    form = NewPostForm(request.POST)
    return form

@login_required
@allowed_users(allowed_roles=['Editor'])
def post_delete(request,id):
    selected_blog = Album.objects.get(pk=id)
    selected_blog.delete()
    return redirect(reverse_lazy('Post:admin_postlist'))

Post/views/basicviews.py
from webbrowser import get
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from requests import post
from Post.forms import *
from django.contrib import messages
import datetime
from Post.filters import OrderFilter
from Post.models import post, Author,Album
# Create your views here.

def home(request):
    featured=post.objects.filter(HomePage=True).select_related('album')   
    context = {'featured':featured}
    return render(request, 'home.html', context)

def post_view(request,post_id):
   thepost=get_object_or_404(post.objects.select_related('author'),pk=post_id)

   return render(request, 'post_view.html', {'post':thepost})

def posthome(request):
   
 
    
    items = post.objects.all().order_by('-date_created')
    print(items)
    myFilter = OrderFilter(request.GET, queryset=items)  
    featured=post.objects.filter(FeaturedPost=True)
    posts = myFilter.qs
    tagform = checkboxtags()
    context = {'posts':posts, 'myFilter':myFilter,'tagform':tagform,'featured':featured}
    return render(request, 'post_home.html',context)


   

Post/views/edit_post.py
from django.contrib.auth.decorators import login_required
from Post.decorators import allowed_users
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from Post.forms import *
from django.contrib import messages
import datetime
from Post.filters import OrderFilter

from Post.models import post, Author,Album

@login_required
@allowed_users(allowed_roles=['Editor'])
def editpost(request, id=0):
    #if we are trying to view edit page. If new just show blank form, else show form with 
    # current data in it
    if request.method == "GET":
        if id == 0:
            form = PostForm
        else:
            postupdate= post.objects.get(pk=id)
            form = PostForm(instance=postupdate)
        return render(request, 'edit_post.html', {'form':form})
    #from the form page we hit submit
    else:
        # if a new post
        if id == 0:
            form = PostForm(request.POST)
            
        # editing a existing post    
        else:
            postupdate= post.objects.get(pk=id)
            form = PostForm(request.POST, instance = postupdate)
        
        if form.is_valid():
            print('saved')
            settime=form.save(commit=False)           
            settime.last_edit_date = (datetime.datetime.now())
            settime.save()
            # must save m2m field seperalty after using commit = False
            form.save_m2m()
        else:
            print('did not save')
            print(form.errors)
             
            return render(request, 'edit_post.html',{'form':form})
        
        return redirect(reverse_lazy('Post:admin_postlist'))

Post/templates/admin_postlist.html
{% extends "index.html" %}
{% load static %}




{% block content %}
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />

<script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<style>
	.hidden{
        display:none;
    }

    .result{
    	max-width:auto;
    }
</style>

  <div class="jumbotron">
    <div class="p-5 text-center bg-light" style="margin-top: 10px;">
      <h1 class="mb-3">Post</h1>
    </div>


    <div class="row">
        
            {%if request.user.is_authenticated%}
            <div class="col-md-12">
                <button class="btn btn-outline-success w-100 btn-lg" i class="fas fa-plus" id="add-blog"></i> Add New Post </button>
                
                    <div class="form-add-blog hidden mt-2" style="width: 61%;"  >
                      <form action="{% url 'Post:admin_postlist' %}" method="post" autocomplete = "off" >                       
                          {%csrf_token%}
                          {{form}}                                                   
                          <button type="submit" class="btn btn-sm btn-success m-1"><i class="fas fa-save" ></i>Submit</button>
                      </form>
                    </div>                      
              </div>

            {%else%}
            <button type="submit" class="btn btn-outline-success w-100 btn-lg" data-bs-toggle="modal" data-bs-target="#edit{{item.id}}">
              <i class="fas fa-plus"></i> Add New Post
            </button>
            <div class="modal fade" id="edit{{item.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">User Login Required</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                   You must login to edit items!
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a href="{% url 'members:login' %}"class="btn btn-primary active" role="button" aria-pressed="true">Login</a>
                  </div>
                </div>
              </div>
            </div>
            {%endif%}
        </a>
      </div>
    </div>
  </div>
  <script>
 
    var newId = 4
    var newpost = { 'name': null, 'id': newId, 'Articels': null }
 
    $('#add-blog').on('click', function () {
        $('.form-add-blog').removeClass('hidden')
    })
 
    
   
    </script>
   
<hr>

<br>



<br>

    <!-- Start of Jumbotron -->
        <div class="jumbotron jumbotron-fluid" >

                <hr class="my-4">
                <table  id="datatablesSimple" class="table table-borderless table-striped table-hover table-fixed">
                      <thead class="border-bottom font-weight-bold text-white w-100 ">
                        <tr style="background-color:#214e7f">
                          <th>Title</th>
                          <th>Date Created</th>
                          <th>Last Edit Date</th>
                          <th>Author</th>
                          <th>Home Page</th>
                          <th>Featured</th>

                          <th></th>
                        </tr>
                      </thead>

                      <tbody>
                        {%for item in posts %}

                        <tr>

                            <td>{{item.title}}</td>
                            <td>{{item.date_created}}</td>
                            <td>{{item.last_edit_date}}</td>
                            <td>{{item.author.user.get_full_name}}</td>
                            <td>{{item.HomePage}}</td>
                            <td>{{item.FeaturedPost}}</td>
                            <td>
                              {%if request.user.is_authenticated%}
                              <a href="{% url 'Post:post_update' item.id %}#" class="btn text-secondary">
                                  <i class="far fa-edit fa-lg fa-fw"></i>
                              </a>
                              {%else%}
                              <button type="submit" class="btn" data-bs-toggle="modal" data-bs-target="#edit{{item.id}}">
                                <i class="far fa-edit fa-lg fa-fw"></i>
                              </button>
                              <div class="modal fade" id="edit{{item.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="exampleModalLabel">User Login Required</h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                     You must login to edit items!
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                      <a href="{% url 'members:login' %}"class="btn btn-primary active" role="button" aria-pressed="true">Login</a>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              {%endif%}
                              <a href="{% url 'Post:imageList' item.album.id %}" class="btn text-secondary">
                                <i class="far fa-image fa-lg fa-fw"></i>
                              </a>

                              <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#test{{item.id}}">
                                <i class="far fa-trash-alt fa-lg text-danger fa-fw"></i>
                              </button>
                              <!-- Modal -->

                              {%if request.user.is_authenticated%}
                              <div class="modal fade" id="test{{item.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="exampleModalLabel">Confirm Delete</h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                      Are you sure you want to delete post {{item.album.name}}?
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

                                      <form action="{% url 'Post:post_delete' item.album.id %}" method="post" class="d-inline" >
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-primary">Delete</button>
                                      </form>
                                    </div>
                                  </div>
                                </div>
                              </div>

                              {%else%}
                              <div class="modal fade" id="test{{item.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="exampleModalLabel">User Login Required</h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                     You must login to delete items!
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                      <a href="{% url 'members:login' %}"class="btn btn-primary active" role="button" aria-pressed="true">Login</a>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              {%endif%}

                            </td>
                        </tr>
                        {% endfor %}
                      </tbody>

                </table>



          
                


        </div>

      <!-- End of Jumbotron -->

    
        <script src="{%static 'Post/js/scripts.js'%}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{% static 'Post/js/datatables-simple-demo.js'%}"></script>
    </body>
{% endblock %}

Post/templates/edit_image.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

{%if request.user.is_authenticated%}

    <!-- Start of Jumbotron -->
        <div class="jumbotron">
          <div class="p-5 text-center bg-lite" style="margin-top: 10px;">
            <h1 class="mb-3">Edit Image</h1>
          </div>

          <div class class="container">
                <hr class="my-4">
                <form action=""  enctype="multipart/form-data"  method="post" autocomplete = "off">
                  {%csrf_token%}
               
                    <div class="col-1">
                      {{form.order|as_crispy_field}}
                    </div>
                   
                    <div class="col-1">
                        {{form.default|as_crispy_field}}
                    </div>
                </div>
                
                <div class="row pb-5 ">
                    <div class="col-lg-8 col-md-12">
                        {{form.description|as_crispy_field}}
                    </div>
                                
                </div>

                    <div class="row">
                        {{form.image|as_crispy_field}}
                    </div>
                    
            </div>
            <div class="row">
                <div class="col-md-8">
                  <button type="submit" class="btn btn-success w-100 btn-lg"><i class="fas fa-save"></i>Submit</button>
                </div>
                <div class="col-md-4">
                  <a href="{% url 'Post:imageList' curalbum %}" class="btn btn-secondary w-100 btn-lg">
                      <i class="fas fa-stream"></i>Back to list
                  </a>
                </div>
              </div>

        </div>

      <!-- End of Jumbotron -->
{%else%}
<div class="alert alert-info" role="alert">
  You must log in to Edit!
</div>
{%endif%}



{% endblock %}

Post/templates/index.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="Create Post" content="" />
        <meta name="Brandon Thaller" content="" />
        <title>PostApp</title>
        <!-- Favicon-->
       


        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">   
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
          <!-- Favicon-->
          <link rel="icon" type="image/x-icon" href="{%static '/assets/favicon.ico'%}" />
        
          <!-- Core theme CSS (includes Bootstrap)-->
        
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />

      
    </head>
    <body class=" pb-5">
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Your Name Here </a>


                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                      {%if request.user.is_authenticated%}
                      <span class="nav-item m-auto text-white me-5">Logged In: {{request.user}}</span>
                      <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                      {%else%}
                      <span class="navbar-brand mb-0 h1"></span>
                      <li class="nav-item"><a class="nav-link" href="{% url 'members:login' %}">Login</a></li>
                      {%endif%}

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="operationsDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Stuff</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="operationsDropdown">
                                <li><a class="dropdown-item" href="#">More Stuff</a></li>
                           
                               
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Post:posthome' %}">Post</a></li>
                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                               
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">admin</a></li>
                                <li><a class="dropdown-item" href="{% url 'Post:admin_postlist' %}">Post Admin</a></li>
                               
                          
                              
                               
                            </ul>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
<div class="container-fluid  px-5" style="background-color:daf0ee ;" >


{%if messages%}
  {% for message in messages %}

      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>  {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
  {% endfor %}
{%endif%}

{% block content %}{% endblock %}

</div>


    </body>
    <br>
    <!-- Footer-->
<footer  class="fixed-bottom bg-dark py-4 mt-auto"  >
  <div class="container px-5">
      <div class="row align-items-center justify-content-between flex-column flex-sm-row">
          <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; mysite 2022</div></div>

      </div>
  </div>
</footer>

                <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
          
            
            <!-- Core theme JS-->
         
           
</html>